name: Push

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  GO_VERSION: 1.19

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v4
    - name: Verify
      run: |
        make verify
        git diff --exit-code

  test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v4
    - name: Test
      run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [verify, test]
    if: ${{ github.repository_owner == 'fybrik' }}

    steps:
    - uses: actions/checkout@v4
    # Versions are created as follows:
    # - Tags starting with v will be released as what comes after `v`. (e.g. refs/tags/v1.0 -> 1.0).
    # - Main branch will be released with `main` as version tag for the docker images
    - id: version
      name: Infer version
      run: |
        if [[ ${GITHUB_REF} == refs/tags/* ]] ;
        then
            version="${GITHUB_REF#refs/tags/v}"
        elif  [[ ${GITHUB_REF} == refs/heads/main ]] ;
        then
            version=main
        fi
        echo "DOCKER_TAG=${version}" >> $GITHUB_ENV
    - name: Build docker image 
      run: make docker-build
    - name: Docker push
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}"
        make docker-push
    - run: docker images
